[package]
name = "cosmos-ui-leptos"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.6.12", features = ["csr", "nightly"] }
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
